language: node_js
addons:
  sonarcloud:
    organization: "gotreasa" # the key of the org you chose at step #3
    token:
      secure: "C4dpRGa3kqha7Lowr3ppAYKi7swT+P9fSP9hNtK4UD58c6MJL0WNP+vjoz26IYcoNicOWyIm4Fhh33kYDl8MsW6/m0SSsRDTOyPFGBVefV5d7LTv6l0zd76/jmI0G3f1RW6fBLDe7EH9xlQmbKaQ9PqSnBFQsem30E3wl5Y6O87EzRwkVa5KVtJZRsKeKWWlSd7nMEW/eZygtDgkQjWqNefDGObtvShFzzDsQUCiooJlqdF6LUH7/0WTtsDwng+bdzh4TNdwizrS2MgwjbaESP+yYgtctRdBABgk4pYBfMHe2GxRBq2Kb+FmpYMLfPsfyCAC8CG6/5HfXAAnmrfqsFzrxQ9A7Pv9SspMxw8zySKweq/qla9MUf5KPPjtYyU9ir681BMlaqvLcyj6ivcHY7fcOSC2wbZwhTacXe4bWHGPAhWPn0o3Ql2nxRrjW9shdlqKC8H1O0vwJMj91vbeha1Y7YPDGFZ4pYDxlTp/W1PFM1EU4KCue7kFR0qd1ZbshLn9qIL3BL/i6Ldmm7VP6a+Yg6g4QHueR3q4aWdsmOhZmCqlk1NuWeyCWheIL6wcQhTFI1kgf1JK6yree2KK8DpXGJsEHMcP77SwpoXEY1B6/9zjH0gWunXl9TJ4dSJuDDrwTBJSu2qF4LXAWIKmu+ho/fmN0iIbDIa+rlPjccc="
stages:
- name: Build
- name: Test
- name: Monitor
jobs:
  include:
  - stage: Build
    name: Snyk vulnerability check
    script:
      snyk test
  - language: python
    python: 3.9
    name: Detect secrets in files
    script:
      - pip install --upgrade "git+https://github.com/ibm/detect-secrets.git@master#egg=detect-secrets"
      - detect-secrets-hook --baseline .secrets.baseline $(git ls-files)
  - language: node_js
    name: Run commit lint
    script:
      - commitlint-travis
  - stage: Test
    script:
      - npm test
      - sonar-scanner
  - stage: Monitor
    script:
      snyk monitor
env:
  global:
    # SYNK TOKEN
    secure: "biiKSCm5B0UnEM+RUQ2SpLzxYsF2Hv4X3YcMoUIBoFVqCpd6Ti5AK1Fz0BaMTpw9OGaxYKmcfk1d9YhNMuabJGmTQ8wETvs4QnQc9BYoGcYqCyK/3aZr5ueH5nnv2lxsoEOia25ut86aWzCtPS42gaQjMmt1bvCjJpBWjAIUtvUTWqgBM3Efb8burf2ukvFdqxrmQHngUznDa0hMw0ZbueG88VhlKjU6hMJdYx949j3e19QT6Aqhy+yUNZfhPi28rqEYwHCeC+T9ujPb5oFRsBRhvGngWH2uTum1A8uLHVQ3KeuFIPxR4hPkfdP+cAzJIVu5xpYFlKRPylrym6evqofoRU5CnI+91in1IvpoDRDNEgYJ7yu+15kXDKgiUbOIyw0oG8YPFG4v+ZYPwCeoJhOn2CseRxyDxOZVDZgmdpafVbOkziqV0NmdRFdqehF/B8333YjXj0TtSEY17WBwtgjg31I3niUcG1rtQVObNXyv8sT5YW7ul0gos83bDHfBfVTw0Rc6XerEEku3aTxXvP2UyCD6ie38x7tUqIpVLQJ0Z2AhnudfqJLqi3epCVwvsJDTnf/aNQqbcsoH2g1enWc/5lJtGMKbS93NCTogLSuY/jAIcG8hPH++h985o+w+d9c5NX2Z3/+Dsdgaj0kVsyDwA30vQV56xl9PsH4OVCU="
